version: '3.1'
 
services:
  jenkins:
    image: blackonyx/jenkins:latest
    hostname: jenkins
    ports:
     - "8080:8080"
     - "50000:50000"
    networks:
      - jenkinsnet
    volumes:
     - "./jenkins/jobs:/var/jenkins_home/jobs/"
    secrets:
     - jenkinsUsername
     - jenkinsPassword

  carritodb:
    image: mysql:5.7.21
    restart: always
    networks:
      - jenkinsnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrito_app
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
     - carritodb_data:/var/lib/mysql


  sonarqube:
    image: sonarqube:6.7.3-alpine
    hostname: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkinsnet
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonardb:
    image: postgres:10.3-alpine
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonardb_lib:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - sonardb_data:/var/lib/postgresql/data


networks:
  sonarnet:
    driver: bridge
  jenkinsnet:
    driver: bridge

volumes:
  sonarqube_conf:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_bundled-plugins:
    driver: local
  sonardb_lib:
    driver: local
  sonardb_data:  
    driver: local
  carritodb_data:
    driver: local

secrets:
  jenkinsUsername:
    file: ./jenkins/secrets/jenkinsUsername
  jenkinsPassword:
    file: ./jenkins/secrets/jenkinsPassword
