version: '3.1'
 
services:
  carritodb:
    image: mysql:5.7.21
    restart: always
    networks:
      - tomcatnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrito_app
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
     - carritodb_data:/var/lib/mysql

  tomcat:
    image: blackonyx/tomcat8-alpine
    hostname: tomcat
    restart: always
    networks:
      - tomcatnet
    ports:
      - "8080:8080"


  testlink:
    image: bitnami/testlink:latest
    hostname: testlink
    networks:
      - testlinknet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - testlink_data:/bitnami
    environment:
      - MARIADB_HOST=testlinkdb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=verysecretadminpassword
      - TESTLINK_EMAIL=admin@example.com

  testlinkdb:
    image: bitnami/mariadb:latest
    networks:
      - testlinknet
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - testlinkdb_data:/bitnami
      

  mantisbt:
    image: vimagick/mantisbt:latest
    hostname: mantisbt
    networks:
      - mantisnet
    ports:
      - "8989:80"

  mantisdb:
    image: mysql:latest
    restart: always
    networks:
      - mantisnet
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    volumes:
     - mantisdb_data:/var/lib/mysql


networks:
  tomcatnet:
    driver: bridge
  testlinknet:
    driver: bridge
  mantisnet:
    driver: bridge

volumes:
  carritodb_data:
    driver: local
  mantisdb_data:
    driver: local
  testlinkdb_data:
    driver: local
  testlink_data:
    driver: local

secrets:
  jenkinsUsername:
    file: ./jenkins/secrets/jenkinsUsername
  jenkinsPassword:
    file: ./jenkins/secrets/jenkinsPassword
